# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [15]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    
    # 对最后一维计算指数
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # 减去最大值防止数值溢出
    # 对最后一维归一化
    prob_x = exp_x / np.sum(exp_x, axis=-1, keepdims=True)
    # 将结果转换为 TensorFlow 张量，以便支持 .numpy() 方法
    prob_x = tf.convert_to_tensor(prob_x, dtype=tf.float32)

    ##########

    return prob_x


test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [13]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    
    # 计算 sigmoid 函数
    prob_x = 1 / (1 + np.exp(-x))
    # 将结果转换为 TensorFlow 张量，以便支持 .numpy() 方法
    prob_x = tf.convert_to_tensor(prob_x, dtype=tf.float32)

    ##########

    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''

    loss = -tf.reduce_sum(label * tf.math.log(x + 1e-10), axis=-1)  # 添加 1e-10 防止 log(0)
    loss = tf.reduce_mean(loss)  # 对所有样本取平均
    
    ##########

    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [19]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''

    loss = - (label * tf.math.log(x + 1e-10) + (1 - label) * tf.math.log(1 - x + 1e-10))  # 添加 1e-10 防止 log(0)
    loss = tf.reduce_mean(loss)  # 对所有样本取平均
    ##########

    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]


True